# Generated by Django 3.2.6 on 2021-10-20 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='shopRation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=40)),
                ('aadhar_num', models.IntegerField(unique=True)),
                ('sugar_quant', models.IntegerField()),
                ('wheat_quant', models.IntegerField()),
                ('rice_quant', models.IntegerField()),
                ('date', models.DateField()),
            ],
        ),
    ]
