# Generated by Django 3.2.6 on 2021-10-23 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='custration',
            name='aadhar_num',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='custration',
            name='date',
            field=models.DateField(unique=True),
        ),
    ]
