# Generated by Django 3.2.6 on 2021-10-25 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custApp', '0002_auto_20211023_1954'),
    ]

    operations = [
        migrations.AlterField(
            model_name='custration',
            name='date',
            field=models.DateTimeField(unique=True),
        ),
    ]
