# Generated by Django 3.2.12 on 2022-04-27 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custApp', '0004_auto_20211027_1904'),
    ]

    operations = [
        migrations.AlterField(
            model_name='custration',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
